"""empty message

Revision ID: 2a5f3e4c3210
Revises: 54bef0da8553
Create Date: 2024-04-25 21:53:32.218016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5f3e4c3210'
down_revision = '54bef0da8553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'formation', ['formation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('formation_id')

    # ### end Alembic commands ###
