"""empty message

Revision ID: 975babcd911b
Revises: 2a5f3e4c3210
Create Date: 2024-04-27 01:34:27.908410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975babcd911b'
down_revision = '2a5f3e4c3210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Teacher')
    # ### end Alembic commands ###
